### ISSUE TITLE
Please make complete example

### ISSUE THREAD

**Issue by naturallymitchell** [bronjham-code/easy_state#2]
I have 2 difficulties with the current example:

1) 
> ERROR: package:example/main.dart: Error: No 'main' method found.
> ERROR: Try adding a method named 'main' to your program.

2) I have to manually do `flutter create --platforms=linux .`, add `simple_state` to `pubspec.yaml` dependencies, and then move `main.dart` to `lib/`.  Could you please make it a full example instead of a single file?

**Comment by bronjham-code** [comment]
published an update in which he finalized examples of using the library

**Comment by naturallymitchell** [comment]
thanks 👍
