### ISSUE TITLE
Could simple_state extend/fork event_bus?

### ISSUE THREAD

**Issue by naturallymitchell** [bronjham-code/easy_state#3]
Before https://github.com/bronjham-code/simple_state/commit/23570957868e2413f2c7c6b2a0ebb60293519dab , [EventBus](https://pub.dev/packages/event_bus) and SimpleState both used Streams, and since that library already has a good amount of support, perhaps it's worth exploring.

I'm interested in `simple_state` because your implementation of the [Observer pattern](https://en.wikipedia.org/wiki/Observer_pattern) is a more complete [Event-driven architcture](https://en.wikipedia.org/wiki/Event_driven_architecture) for [ECA Rules](https://en.wikipedia.org/wiki/Event_condition_action).

**Comment by ChessMax** [comment]
AFAIK there are no plans to extend/fork EventBus.
