### ISSUE TITLE
Todo state management example

### ISSUE THREAD

**Issue by naturallymitchell** [bronjham-code/easy_state#4]
[Flutter State Management packages](https://fluttergems.dev/state-management/) widely use the Todo App example as a simple illustration for feature comparison.

Examples:
- [Riverpod Todo](https://github.com/rrousselGit/riverpod/tree/master/examples/todos)
- [Bloc Todo](https://github.com/felangel/bloc/tree/master/examples/flutter_todos) (with [Flutter Todos Tutorial](https://bloclibrary.dev/#/fluttertodostutorial))
- [Mobx Todo](https://github.com/mobxjs/mobx.dart/tree/master/mobx_examples/lib/todos) (great example)
- [EventBus Todo](https://github.com/Barttje/todolist_event_bus) (seems broken)
- [Streams / GetX / Bloc Todos](https://github.com/vemarav/flutter_todo) (wow, what potential)
- [Provider Todo](https://github.com/EcemBostancioglu/todo_app)
- [Binder Todo](https://github.com/letsar/binder/tree/main/examples/todos) (I like this one)
- [TodoMVC for Flutter!](https://github.com/brianegan/flutter_architecture_samples)

@bronjham-code , do you need help with this? (I'm not a coder, but I could possibly find a freelancer.)  How would you want the example to look? (There's a bit of variety in the implementations.)

**Comment by ChessMax** [comment]
Thanks for your suggestion. [Here](https://github.com/bronjham-code/simple_state/tree/example_todo_app/example/todo_app) has been added an example of Todo app with simple state. It needs some polish but overall should be ok.

I'm just wondering why are you interested in this if you are not a coder?

**Comment by bronjham-code** [comment]
example merged into master branch
